# Generated by Django 4.1.1 on 2022-09-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parser_Ozon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasdel', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sales_id', models.IntegerField()),
                ('sales_name', models.CharField(max_length=50)),
                ('sales_credentials', models.CharField(max_length=1000)),
            ],
        ),
    ]
